name: mi_entorno
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - openpyxl
  - xlrd 
  - requests
  - python-dotenv
  - jupyterlab
  - matplotlib
  - pip:
      - python-decouple
